# Generated by Django 2.1.1 on 2018-11-19 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('time1', models.BigIntegerField()),
                ('time2', models.BigIntegerField()),
                ('winer', models.CharField(default=None, max_length=30, null=True)),
                ('desc', models.CharField(default=None, max_length=300, null=True)),
                ('battle_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('game_win', models.IntegerField()),
                ('game_lose', models.IntegerField()),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=420)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('winning_rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=30, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='CodeWar.CodingUser')),
                ('invitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitor', to='CodeWar.CodingUser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(max_length=30)),
                ('room_slogan', models.CharField(default='come on to battle!', max_length=100, null=True)),
                ('user1_state', models.CharField(max_length=30, null=True)),
                ('user2_state', models.CharField(max_length=30, null=True)),
                ('user3_state', models.CharField(max_length=30, null=True)),
                ('user4_state', models.CharField(max_length=30, null=True)),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_ower_user', to='CodeWar.CodingUser')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user1', to='CodeWar.CodingUser')),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_user2', to='CodeWar.CodingUser')),
                ('user3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_user3', to='CodeWar.CodingUser')),
                ('user4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_user4', to='CodeWar.CodingUser')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='CodeWar.Room'),
        ),
        migrations.AddField(
            model_name='battle',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeWar.Question'),
        ),
        migrations.AddField(
            model_name='battle',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_user1', to='CodeWar.CodingUser'),
        ),
        migrations.AddField(
            model_name='battle',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_user2', to='CodeWar.CodingUser'),
        ),
        migrations.AddField(
            model_name='battle',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_user3', to='CodeWar.CodingUser'),
        ),
        migrations.AddField(
            model_name='battle',
            name='user4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_user4', to='CodeWar.CodingUser'),
        ),
    ]
